- name: Copy k3s API server CA certificate to k3s cert store
  ansible.builtin.copy:
    src: /tmp/server-ca.crt
    dest: /etc/rancher/k3s/server-ca.crt
    owner: root
    group: root
    mode: "0644"
    force: no
